In [1]:
import os
import sys
import numpy as np
import pandas as pd
import seaborn as sns
import pyarrow as pa
import polars as pl
from matplotlib import pyplot as plt
from deltalake import DeltaTable, write_deltalake

In [2]:
sys.path.append(str("/root/capsule/src/"))

In [3]:
from connects_common_connectivity.models import (
    DataSet,
    Modality,
    DataItem,
    DataItemDataSetAssociation,
    Unit,
    CellFeatureDefinition,
    CellFeatureSet,
)

from connects_common_connectivity.arrow_utils import (
    build_arrow_schema,
    models_to_table,
    attach_linkml_metadata,
    build_cell_feature_matrix_schema,
)

# VISp inhib morph features

In [4]:
units_df = pd.read_csv("/data/visp-features-and-mapping/inh_visp_patchseq_morph_feature_definitions.csv")

In [5]:
units_df

,id,description,unit,data_type,range_min,range_max
0,axon_bias_x,Difference in axon extent in the x-dimension (...,MICRONS_LENGTH,<f4,0.0,NaN
1,axon_bias_y,Difference in axon extent in the y-dimension (...,MICRONS_LENGTH,<f4,NaN,NaN
2,axon_depth_pc_0,First principal component of PCA performed on ...,NONE,<f4,NaN,NaN
3,axon_depth_pc_1,Second principal component of PCA performed on...,NONE,<f4,NaN,NaN
4,axon_depth_pc_2,Third principal component of PCA performed on ...,NONE,<f4,NaN,NaN
5,axon_depth_pc_3,Fourth principal component of PCA performed on...,NONE,<f4,NaN,NaN
6,axon_depth_pc_4,Fifth principal component of PCA performed on ...,NONE,<f4,NaN,NaN
7,axon_depth_pc_5,Sixth principal component of PCA performed on ...,NONE,<f4,NaN,NaN
8,axon_emd_with_basal_dendrite,Earth mover’s distance metric calculated using...,ARBITRARY_UNIT,<f4,0.0,NaN
9,axon_exit_distance,The path distance from the soma surface to the...,MICRONS_LENGTH,<f4,0.0,NaN
10,axon_exit_theta,Normalized radial position of the point where ...,RATIO,<f4,0.0,1.0
11,axon_extent_x,Total extent of the axon in the x-direction (p...,MICRONS_LENGTH,<f4,0.0,NaN
12,axon_extent_y,Total extent of the axon in the y-direction (p...,MICRONS_LENGTH,<f4,0.0,NaN
13,axon_frac_above_basal_dendrite,Fraction of axon nodes located above the highe...,RATIO,<f4,0.0,1.0
14,axon_frac_below_basal_dendrite,Fraction of axon nodes located below the lowes...,RATIO,<f4,0.0,1.0
15,axon_frac_intersect_basal_dendrite,Fraction of axon nodes located between the hig...,RATIO,<f4,0.0,1.0
16,axon_max_branch_order,The maximum number of bifurcations encountered...,COUNT,<u4,0.0,NaN
17,axon_max_euclidean_distance,The direct-line distance from the soma to the ...,MICRONS_LENGTH,<f4,0.0,NaN
18,axon_max_path_distance,The longest path length from the soma to an ax...,MICRONS_LENGTH,<f4,0.0,NaN
19,axon_mean_contraction,The average of the ratios of the summed euclid...,RATIO,<f4,0.0,1.0
20,axon_num_branches,The number of individual axon branches,COUNT,<u4,0.0,NaN
21,axon_soma_percentile_x,Percentile of the x-coordinate of the soma wit...,RATIO,<f4,0.0,0.5
22,axon_soma_percentile_y,Percentile of the y-coordinate of the soma wit...,RATIO,<f4,0.0,1.0
23,axon_total_length,The combined length of all axon branches,MICRONS_LENGTH,<f4,0.0,NaN
24,basal_dendrite_bias_x,Difference in basal dendrite extent in the x-d...,MICRONS_LENGTH,<f4,NaN,NaN
25,basal_dendrite_bias_y,Difference in basal dendrite extent in the y-d...,MICRONS_LENGTH,<f4,NaN,NaN
26,basal_dendrite_calculate_number_of_stems,Number of dendrite stems emerging from the soma,COUNT,<u4,0.0,NaN
27,basal_dendrite_extent_x,Total extent of the basal dendrites in the x-d...,MICRONS_LENGTH,<f4,0.0,NaN
28,basal_dendrite_extent_y,Total extent of the basal dendrites in the y-d...,MICRONS_LENGTH,<f4,0.0,NaN
29,basal_dendrite_frac_above_axon,Fraction of basal dendrite nodes located above...,RATIO,<f4,0.0,1.0
30,basal_dendrite_frac_below_axon,Fraction of basal dendrite nodes located below...,RATIO,<f4,0.0,1.0
31,basal_dendrite_frac_intersect_axon,Fraction of basal dendrite nodes located betwe...,RATIO,<f4,0.0,1.0
32,basal_dendrite_max_branch_order,The maximum number of bifurcations encountered...,COUNT,<u4,0.0,NaN
33,basal_dendrite_max_euclidean_distance,The direct-line distance from the soma to the ...,MICRONS_LENGTH,<f4,0.0,NaN
34,basal_dendrite_max_path_distance,The longest path length from the soma to a bas...,MICRONS_LENGTH,<f4,0.0,NaN
35,basal_dendrite_mean_contraction,The average of the ratios of the summed euclid...,RATIO,<f4,0.0,1.0
36,basal_dendrite_mean_diameter,The average diameter of basal dendrite compart...,MICRONS_LENGTH,<f4,0.0,NaN
37,basal_dendrite_num_branches,The number of individual basal dendrite branches,COUNT,<u4,0.0,NaN
38,basal_dendrite_soma_percentile_x,Percentile of the x-coordinate of the soma wit...,RATIO,<f4,0.0,0.5
39,basal_dendrite_soma_percentile_y,Percentile of the y-coordinate of the soma wit...,RATIO,<f4,0.0,1.0
40,basal_dendrite_stem_exit_down,Fraction of basal dendrite stems emerging from...,RATIO,<f4,0.0,1.0
41,basal_dendrite_stem_exit_side,Fraction of basal dendrite stems emerging from...,RATIO,<f4,0.0,1.0
42,basal_dendrite_stem_exit_up,Fraction of basal dendrite stems emerging from...,RATIO,<f4,0.0,1.0
43,basal_dendrite_total_length,The combined length of all basal dendrite bran...,MICRONS_LENGTH,<f4,0.0,NaN
44,basal_dendrite_total_surface_area,The combined surface area of all basal dendrit...,MICRONS_SQUARE,<f4,0.0,NaN
45,soma_aligned_dist_from_pia,Distance between the pia and the soma after al...,MICRONS_LENGTH,<f4,0.0,NaN

In [6]:
ft_defs = []
for idx, row in units_df.iterrows():
    ft_def = CellFeatureDefinition(
        id=str(row['id']),
        description=str(row['description']),
        unit=str(row['unit']),
        data_type=str(row['data_type']),
        range_min=float(row['range_min']),
        range_max=float(row['range_max']),
    )
    ft_defs.append(ft_def)

In [7]:
schema = build_arrow_schema(CellFeatureDefinition)
table = models_to_table(ft_defs, schema)
table = attach_linkml_metadata(table, linkml_class="CellFeatureDefinition")  # version auto-populated

In [8]:
PATH = "../results/cellfeaturedefinition/visp_inh"
write_deltalake(PATH, table, mode="append")

In [9]:
cell_feature_set = CellFeatureSet(
    id='inh_visp_morph_features',
    description='Cell features used for analysis and MET-type definition for inhibitory cortical Patch-seq neurons',
    feature_definition_ids=[fd.id for fd in ft_defs],
    extraction_method='Computed via https://github.com/AllenInstitute/skeleton_keys.'
)

In [10]:
schema = build_arrow_schema(CellFeatureSet)
table = models_to_table([cell_feature_set], schema)
table = attach_linkml_metadata(table, linkml_class="CellFeatureSet")  # version auto-populated

PATH = "../results/cellfeatureset/visp_inh"
write_deltalake(PATH, table, mode="append")

In [11]:
schema = build_cell_feature_matrix_schema(cell_feature_set, ft_defs, cell_index_column="id")

In [12]:
data_feature_matrix = pd.read_csv("/data/visp-features-and-mapping/inh_ivscc_features_wide_unnormalized.csv")

In [13]:
data_feature_matrix

,specimen_id,axon_bias_x,axon_bias_y,axon_depth_pc_0,axon_depth_pc_1,axon_depth_pc_2,axon_depth_pc_3,axon_depth_pc_4,axon_depth_pc_5,axon_emd_with_basal_dendrite,...,basal_dendrite_mean_diameter,basal_dendrite_num_branches,basal_dendrite_soma_percentile_x,basal_dendrite_soma_percentile_y,basal_dendrite_stem_exit_down,basal_dendrite_stem_exit_side,basal_dendrite_stem_exit_up,basal_dendrite_total_length,basal_dendrite_total_surface_area,soma_aligned_dist_from_pia
0,601506507,180.833198,-249.830744,-255.225090,23.857132,-264.429951,-299.517754,-400.345397,28.557966,22.687988,...,0.918386,22.0,0.137298,0.522513,0.000000,0.500000,0.500000,2518.295630,7207.459813,357.159826
1,601790961,25.481124,434.251083,-216.809886,-153.378458,-303.881835,-117.440692,241.134085,-7.542952,39.412388,...,0.870701,42.0,0.480986,0.462676,0.000000,0.666667,0.333333,4256.093901,11691.149209,663.103005
2,601803754,42.650596,104.697843,1157.152004,3052.272959,-16.743603,996.874807,318.205713,-209.400944,16.735521,...,0.882682,62.0,0.460057,0.333470,0.125000,0.625000,0.250000,4108.235412,11384.542643,170.365060
3,601808698,42.200019,342.307240,277.368079,-594.419412,-899.916702,833.364479,-405.968840,475.309877,10.474801,...,0.729696,42.0,0.316378,0.047513,0.000000,1.000000,0.000000,2309.168299,5284.628374,460.737871
4,601810307,89.759903,239.040891,1201.597360,-121.156464,890.413919,-553.118489,130.516992,254.212458,12.408631,...,0.834698,48.0,0.454165,0.198232,0.333333,0.666667,0.000000,3226.120636,8470.180595,271.649192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,992386952,16.392923,-109.526470,414.096515,9.791075,90.525572,-78.477266,-298.057252,-51.636147,24.289362,...,0.721978,27.0,0.241616,0.198933,0.000000,1.000000,0.000000,2307.122538,5088.249125,103.263504
516,992830261,93.658339,0.897162,-870.550429,-27.656963,517.408296,209.947128,-119.900792,112.955596,21.176288,...,0.669456,52.0,0.381341,0.383921,0.333333,0.666667,0.000000,3482.194884,7312.632229,647.564011
517,993243528,59.664688,-291.172271,157.466482,114.334986,115.102503,-351.831818,-321.849646,54.609863,18.277459,...,0.710571,47.0,0.395349,0.123575,0.200000,0.600000,0.200000,3264.027546,7252.320477,131.319709
518,993245688,79.241519,-252.564319,2101.276636,-1077.178481,853.407032,21.100093,458.230008,-67.524807,16.590548,...,0.852397,55.0,0.463691,0.219187,0.200000,0.800000,0.000000,4241.089015,11243.586458,207.960281
519,993283588,53.883000,30.718791,451.072446,404.276255,352.611376,-412.538782,-144.668960,359.521598,2.415364,...,0.913803,44.0,0.414325,0.177697,0.250000,0.250000,0.500000,1895.326187,5564.109901,149.393489

In [14]:
df = data_feature_matrix.drop("specimen_id", axis=1)
df['project_id'] = 'visp_inh_patchseq'
df['feature_set_id'] = 'inh_visp_morph_features'

df['id'] = data_feature_matrix['specimen_id'].astype('string')

In [15]:
# go through and cast the types of each column according to the cell feature definitions
for cfd in ft_defs:
    col = cfd.id
    df[col] = df[col].astype(np.dtype(cfd.data_type))

In [16]:
table = pa.Table.from_pandas(df, schema=schema, preserve_index=False)

In [17]:
PATH = "../results/cellfeatures/inh_morph_features/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id", "feature_set_id"])

In [18]:
feat_df = pl.read_delta(PATH)

In [19]:
feat_df

shape: (520, 49)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ axon_bias ┆ axon_bias ┆ axon_dept ┆ … ┆ basal_den ┆ soma_alig ┆ project_i ┆ feature_ │
│ ---       ┆ _x        ┆ _y        ┆ h_pc_0    ┆   ┆ drite_tot ┆ ned_dist_ ┆ d         ┆ set_id   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_surfac ┆ from_pia  ┆ ---       ┆ ---      │
│           ┆ f32       ┆ f32       ┆ f32       ┆   ┆ e_a…      ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f32       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 601506507 ┆ 180.83319 ┆ -249.8307 ┆ -255.2250 ┆ … ┆ 7207.4599 ┆ 357.15982 ┆ visp_inh_ ┆ inh_visp │
│           ┆ 1         ┆ 5         ┆ 98        ┆   ┆ 61        ┆ 1         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 601790961 ┆ 25.481123 ┆ 434.25106 ┆ -216.8098 ┆ … ┆ 11691.149 ┆ 663.10302 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 8         ┆ 91        ┆   ┆ 414       ┆ 7         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 601803754 ┆ 42.650597 ┆ 104.69784 ┆ 1157.1519 ┆ … ┆ 11384.542 ┆ 170.36506 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 5         ┆ 78        ┆   ┆ 969       ┆ 7         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 601808698 ┆ 42.20002  ┆ 342.30725 ┆ 277.36807 ┆ … ┆ 5284.6284 ┆ 460.73788 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 1         ┆ 3         ┆   ┆ 18        ┆ 5         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 601810307 ┆ 89.759903 ┆ 239.04089 ┆ 1201.5974 ┆ … ┆ 8470.1806 ┆ 271.6492  ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 4         ┆ 12        ┆   ┆ 64        ┆           ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 992386952 ┆ 16.392923 ┆ -109.5264 ┆ 414.09652 ┆ … ┆ 5088.2490 ┆ 103.26350 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 74        ┆ 7         ┆   ┆ 23        ┆ 4         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 992830261 ┆ 93.65834  ┆ 0.897162  ┆ -870.5504 ┆ … ┆ 7312.6323 ┆ 647.56402 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆           ┆ 15        ┆   ┆ 24        ┆ 6         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 993243528 ┆ 59.664688 ┆ -291.1722 ┆ 157.46647 ┆ … ┆ 7252.3203 ┆ 131.31970 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 72        ┆ 6         ┆   ┆ 12        ┆ 2         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 993245688 ┆ 79.241516 ┆ -252.5643 ┆ 2101.2766 ┆ … ┆ 11243.586 ┆ 207.96028 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆ 16        ┆ 11        ┆   ┆ 914       ┆ 1         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 993283588 ┆ 53.882999 ┆ 30.718792 ┆ 451.07244 ┆ … ┆ 5564.1098 ┆ 149.39349 ┆ visp_inh_ ┆ inh_visp │
│           ┆           ┆           ┆ 9         ┆   ┆ 63        ┆ 4         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# VISp excitatory morph features

In [20]:
units_df = pd.read_csv("/data/visp-features-and-mapping/exc_visp_patchseq_morph_feature_definitions.csv")

In [21]:
units_df

,id,description,unit,data_type,range_min,range_max
0,apical_dendrite_bias_x,Difference in apical dendrite extent in the x-...,MICRONS_LENGTH,<f4,0.0,NaN
1,apical_dendrite_bias_y,Difference in apical dendrite extent in the y-...,MICRONS_LENGTH,<f4,NaN,NaN
2,apical_dendrite_depth_pc_0,First principal component of PCA performed on ...,NONE,<f4,NaN,NaN
3,apical_dendrite_depth_pc_1,Second principal component of PCA performed on...,NONE,<f4,NaN,NaN
4,apical_dendrite_depth_pc_2,Third principal component of PCA performed on ...,NONE,<f4,NaN,NaN
5,apical_dendrite_depth_pc_3,Fourth principal component of PCA performed on...,NONE,<f4,NaN,NaN
6,apical_dendrite_early_branch_path,Ratio of the maximum length of all the shorter...,RATIO,<f4,0.0,1.0
7,apical_dendrite_emd_with_basal_dendrite,Earth mover’s distance metric calculated using...,ARBITRARY_UNIT,<f4,0.0,NaN
8,apical_dendrite_extent_x,Total extent of the apical dendrite in the x-d...,MICRONS_LENGTH,<f4,0.0,NaN
9,apical_dendrite_extent_y,Total extent of the apical dendrite in the y-d...,MICRONS_LENGTH,<f4,0.0,NaN
10,apical_dendrite_frac_above_basal_dendrite,Fraction of apical dendrite nodes located abov...,RATIO,<f4,0.0,1.0
11,apical_dendrite_frac_below_basal_dendrite,Fraction of apical dendrite nodes located belo...,RATIO,<f4,0.0,1.0
12,apical_dendrite_frac_intersect_basal_dendrite,Fraction of apical dendrite nodes located betw...,RATIO,<f4,0.0,1.0
13,apical_dendrite_max_branch_order,The maximum number of bifurcations encountered...,COUNT,<u4,0.0,NaN
14,apical_dendrite_max_euclidean_distance,The direct-line distance from the soma to the ...,MICRONS_LENGTH,<f4,0.0,NaN
15,apical_dendrite_max_path_distance,The longest path length from the soma to an ap...,MICRONS_LENGTH,<f4,0.0,NaN
16,apical_dendrite_mean_contraction,The average of the ratios of the summed euclid...,RATIO,<f4,0.0,1.0
17,apical_dendrite_mean_diameter,The average diameter of apical dendrite compar...,MICRONS_LENGTH,<f4,0.0,NaN
18,apical_dendrite_mean_moments_along_max_distanc...,Average relative position of bifurcations proj...,RATIO,<f4,0.0,1.0
19,apical_dendrite_num_branches,The number of individual apical dendrite branches,COUNT,<u4,0.0,NaN
20,apical_dendrite_num_outer_bifurcations,The number of bifurcations found in the outer ...,NONE,<f4,0.0,NaN
21,apical_dendrite_soma_percentile_x,Percentile of the x-coordinate of the soma wit...,RATIO,<f4,0.0,0.5
22,apical_dendrite_soma_percentile_y,Percentile of the y-coordinate of the soma wit...,RATIO,<f4,0.0,1.0
23,apical_dendrite_std_moments_along_max_distance...,Standard deviation of the relative position of...,RATIO,<f4,0.0,1.0
24,apical_dendrite_total_length,The combined length of all apical dendrite bra...,MICRONS_LENGTH,<f4,0.0,NaN
25,apical_dendrite_total_surface_area,The combined surface area of all apical dendri...,MICRONS_SQUARE,<f4,0.0,NaN
26,axon_exit_distance,The path distance from the soma surface to the...,MICRONS_LENGTH,<f4,0.0,NaN
27,axon_exit_theta,Normalized radial position of the point where ...,RATIO,<f4,0.0,1.0
28,basal_dendrite_bias_x,Difference in basal dendrite extent in the x-d...,MICRONS_LENGTH,<f4,NaN,NaN
29,basal_dendrite_bias_y,Difference in basal dendrite extent in the y-d...,MICRONS_LENGTH,<f4,NaN,NaN
30,basal_dendrite_calculate_number_of_stems,Number of dendrite stems emerging from the soma,COUNT,<u4,0.0,NaN
31,basal_dendrite_extent_x,Total extent of the basal dendrites in the x-d...,MICRONS_LENGTH,<f4,0.0,NaN
32,basal_dendrite_extent_y,Total extent of the basal dendrites in the y-d...,MICRONS_LENGTH,<f4,0.0,NaN
33,basal_dendrite_frac_above_apical_dendrite,Fraction of basal dendrite nodes located above...,RATIO,<f4,0.0,1.0
34,basal_dendrite_frac_below_apical_dendrite,Fraction of basal dendrite nodes located below...,RATIO,<f4,0.0,1.0
35,basal_dendrite_frac_intersect_apical_dendrite,Fraction of basal dendrite nodes located betwe...,RATIO,<f4,0.0,1.0
36,basal_dendrite_max_branch_order,The maximum number of bifurcations encountered...,COUNT,<u4,0.0,NaN
37,basal_dendrite_max_euclidean_distance,The direct-line distance from the soma to the ...,MICRONS_LENGTH,<f4,0.0,NaN
38,basal_dendrite_max_path_distance,The longest path length from the soma to a bas...,MICRONS_LENGTH,<f4,0.0,NaN
39,basal_dendrite_mean_contraction,The average of the ratios of the summed euclid...,RATIO,<f4,0.0,1.0
40,basal_dendrite_mean_diameter,The average diameter of basal dendrite compart...,MICRONS_LENGTH,<f4,0.0,NaN
41,basal_dendrite_num_branches,The number of individual basal dendrite branches,COUNT,<u4,0.0,NaN
42,basal_dendrite_soma_percentile_x,Percentile of the x-coordinate of the soma wit...,RATIO,<f4,0.0,0.5
43,basal_dendrite_soma_percentile_y,Percentile of the y-coordinate of the soma wit...,RATIO,<f4,0.0,1.0
44,basal_dendrite_stem_exit_down,Fraction of basal dendrite stems emerging from...,RATIO,<f4,0.0,1.0
45,basal_dendrite_stem_exit_side,Fraction of basal dendrite stems emerging from...,RATIO,<f4,0.0,1.0
46,basal_dendrite_stem_exit_up,Fraction of basal dendrite stems emerging from...,RATIO,<f4,0.0,1.0
47,basal_dendrite_total_length,The combined length of all basal dendrite bran...,MICRONS_LENGTH,<f4,0.0,NaN
48,basal_dendrite_total_surface_area,The combined surface area of all basal dendrit...,MICRONS_SQUARE,<f4,0.0,NaN
49,soma_aligned_dist_from_pia,Distance between the pia and the soma after al...,MICRONS_LENGTH,<f4,0.0,NaN

In [22]:
ft_defs = []
for idx, row in units_df.iterrows():
    ft_def = CellFeatureDefinition(
        id=str(row['id']),
        description=str(row['description']),
        unit=str(row['unit']),
        data_type=str(row['data_type']),
        range_min=float(row['range_min']),
        range_max=float(row['range_max']),
    )
    ft_defs.append(ft_def)

In [23]:
schema = build_arrow_schema(CellFeatureDefinition)
table = models_to_table(ft_defs, schema)
table = attach_linkml_metadata(table, linkml_class="CellFeatureDefinition")  # version auto-populated

In [24]:
PATH = "../results/cellfeaturedefinition/visp_exc"
write_deltalake(PATH, table, mode="append")

In [25]:
cell_feature_set = CellFeatureSet(
    id='exc_visp_morph_features',
    description='Cell features used for analysis and MET-type definition for inhibitory cortical Patch-seq neurons',
    feature_definition_ids=[fd.id for fd in ft_defs],
    extraction_method='Computed via https://github.com/AllenInstitute/skeleton_keys.'
)

In [26]:
schema = build_arrow_schema(CellFeatureSet)
table = models_to_table([cell_feature_set], schema)
table = attach_linkml_metadata(table, linkml_class="CellFeatureSet")  # version auto-populated

PATH = "../results/cellfeatureset/visp_exc"
write_deltalake(PATH, table, mode="append")

In [27]:
schema = build_cell_feature_matrix_schema(cell_feature_set, ft_defs, cell_index_column="id")

In [28]:
# Patch-seq morph features
data_feature_matrix = pd.read_csv("/data/visp-features-and-mapping/morph_features_mMET_exc_wide_unnormalized.csv")

In [29]:
data_feature_matrix

,specimen_id,apical_dendrite_bias_x,apical_dendrite_bias_y,apical_dendrite_depth_pc_0,apical_dendrite_depth_pc_1,apical_dendrite_depth_pc_2,apical_dendrite_depth_pc_3,apical_dendrite_early_branch_path,apical_dendrite_emd_with_basal_dendrite,apical_dendrite_extent_x,...,basal_dendrite_mean_diameter,basal_dendrite_num_branches,basal_dendrite_soma_percentile_x,basal_dendrite_soma_percentile_y,basal_dendrite_stem_exit_down,basal_dendrite_stem_exit_side,basal_dendrite_stem_exit_up,basal_dendrite_total_length,basal_dendrite_total_surface_area,soma_aligned_dist_from_pia
0,601628311,147.076721,388.737332,-0.134846,-7.323705,-16.315251,2.834573,0.377581,63.287174,303.832247,...,0.738017,29.0,0.210607,0.859339,0.00,1.000000,0.000000,1842.712482,4251.727723,543.539902
1,603229579,117.918472,513.295648,181.612081,-49.761568,75.880212,18.681380,0.272368,49.580831,323.203125,...,0.678512,30.0,0.468498,0.894992,0.00,1.000000,0.000000,1559.948300,3349.079209,541.661529
2,603337985,74.871318,382.301002,-77.738239,-19.625268,-50.744753,-86.666445,0.384813,13.400124,254.446243,...,0.635489,28.0,0.223268,0.305389,0.25,0.500000,0.250000,1467.914882,2933.822544,458.134219
3,603481505,130.585618,424.042586,309.580620,-48.441029,104.774864,-43.013513,0.370210,45.136786,355.122409,...,0.836733,42.0,0.395452,0.840821,0.00,0.833333,0.166667,2744.146833,7285.432249,498.644308
4,603511210,15.832649,472.387609,-14.175712,70.002755,-47.532825,-23.029360,0.430200,58.767808,185.047517,...,1.043034,52.0,0.458953,0.697552,0.00,1.000000,0.000000,3741.880551,12434.022965,467.544831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,1036259470,228.209968,320.424416,-147.339173,-42.495121,-8.410686,126.120305,0.713882,18.904243,367.508294,...,0.752672,21.0,0.427015,0.654684,0.20,0.600000,0.200000,1302.648057,3058.151016,902.189119
385,1039243792,47.861325,-19.775071,-153.537471,-11.667367,-42.131647,73.554038,0.675558,5.084050,327.860486,...,0.709122,6.0,0.296593,0.044088,0.50,0.500000,0.000000,602.683781,1340.126098,832.825477
386,1039273993,276.587273,495.311917,-116.335457,-47.326925,3.769657,45.892703,0.246732,42.765763,399.540591,...,0.820395,20.0,0.342886,0.735926,0.00,1.000000,0.000000,1384.082446,3628.216524,909.886408
387,1039503078,85.594834,226.283485,-132.778654,0.083811,-30.549618,12.146968,0.145168,17.924472,128.257085,...,0.819520,20.0,0.298099,0.163498,0.25,0.750000,0.000000,1663.345223,4280.269414,913.240052
388,1043809804,144.064767,217.403050,-168.755952,-45.230516,6.413441,95.073826,0.727147,29.577398,449.723109,...,0.735417,21.0,0.205236,0.677365,0.00,1.000000,0.000000,1585.481788,3650.468030,905.232783

In [30]:
ps_df = data_feature_matrix.drop("specimen_id", axis=1)
ps_df['project_id'] = 'visp_exc_patchseq'
ps_df['feature_set_id'] = 'exc_visp_morph_features'

ps_df['id'] = data_feature_matrix['specimen_id'].astype('string')

In [31]:
# WNM morph features
data_feature_matrix = pd.read_csv("/data/visp-features-and-mapping/RawFeaturesWide_ChamferCorr.csv", index_col=0)

In [32]:
data_feature_matrix

,swc_path,soma_aligned_dist_from_pia,basal_dendrite_max_euclidean_distance,apical_dendrite_num_branches,basal_dendrite_stem_exit_down,apical_dendrite_bias_y,apical_dendrite_extent_y,apical_dendrite_depth_pc_0,apical_dendrite_early_branch_path,apical_dendrite_mean_contraction,...,apical_dendrite_extent_x,apical_dendrite_std_moments_along_max_distance_projection,apical_dendrite_num_outer_bifurcations,apical_dendrite_max_path_distance,apical_dendrite_depth_pc_1,basal_dendrite_calculate_number_of_stems,basal_dendrite_mean_contraction,apical_dendrite_bias_x,basal_dendrite_bias_x,basal_dendrite_frac_below_apical_dendrite
0,17109_6201-X4328-Y6753_reg,755.648634,153.118741,13.112095,0.519306,51.220063,130.348098,-127.799230,0.812125,0.919582,...,92.771122,0.095100,0.017473,188.477520,-4.550537,2.025048,0.924001,116.965793,73.426861,0.038531
1,17109_6301-X4756-Y24516_reg,779.803826,158.644468,11.710442,0.346235,29.822118,187.891473,-125.915996,0.464351,0.942480,...,133.943725,0.047786,0.017473,298.755658,-2.846434,3.016802,0.954847,68.235786,20.734153,-0.005611
2,17109_6601-X4384-Y7436_reg,727.831495,218.932446,18.718725,0.000094,53.307739,162.011671,-130.399448,0.573624,0.931142,...,139.756745,0.170515,0.759907,229.434422,-9.068610,2.025048,0.928544,144.969883,46.419273,0.232868
3,17109_6601-X5417-Y25287_reg,753.796313,163.343819,18.718725,0.000094,-134.153298,160.406543,-134.813898,0.610748,0.945982,...,153.129434,0.140594,0.017473,296.258962,-6.212346,4.008555,0.914963,18.596118,13.985249,-0.005611
4,17109_6801-X7432-Y4405_reg,616.766200,210.691787,14.513755,0.259700,-152.226616,176.436476,-128.454254,0.393457,0.908202,...,149.504220,0.169069,0.304686,340.347681,-7.067314,4.008555,0.922157,175.735165,34.455671,-0.005611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,220308_8021-X22273-Y14515_reg,896.101355,154.007736,31.333636,0.000094,426.478646,508.423961,-89.878750,0.301818,0.843487,...,171.156424,0.348784,0.927916,584.360151,-42.625012,3.016802,0.847473,27.566970,64.863695,0.052311
342,220309_5824-X3486-Y10261_reg,606.551544,340.180443,29.931981,0.000094,511.616625,712.083170,-29.732973,0.438712,0.873898,...,305.753978,0.206086,0.591899,659.719187,-44.856429,5.992063,0.851315,28.460744,58.614060,0.058337
343,220309_6744-X9496-Y18547_reg,273.802444,194.949396,31.333636,0.173165,246.234974,307.956904,54.324096,0.540375,0.890393,...,254.576710,0.263005,1.047120,417.626183,19.109618,5.992063,0.839626,2.705247,43.218620,0.153476
344,220315_6442-X7542-Y17434_reg,404.821656,163.812376,25.727008,0.000094,225.254902,479.609711,-64.358903,0.473110,0.903657,...,250.183733,0.251633,0.472695,455.991818,-11.938175,4.008555,0.884905,38.164678,23.977165,-0.005611
345,221686_5481-X4093-Y13144_reg,713.528840,337.971232,25.727008,0.259700,-309.112977,352.985678,-151.097797,0.424888,0.860099,...,226.642119,0.171070,0.472695,540.607749,-17.439567,4.008555,0.857207,103.908356,11.092597,-0.005611

In [33]:
wnm_df = data_feature_matrix.drop(["swc_path"], axis=1)
wnm_df['project_id'] = 'visp_exc_wnm'
wnm_df['feature_set_id'] = 'exc_visp_morph_features'

wnm_df['id'] = data_feature_matrix['swc_path'].astype('string')

In [34]:
df = pd.concat([ps_df, wnm_df])

In [35]:
df

,apical_dendrite_bias_x,apical_dendrite_bias_y,apical_dendrite_depth_pc_0,apical_dendrite_depth_pc_1,apical_dendrite_depth_pc_2,apical_dendrite_depth_pc_3,apical_dendrite_early_branch_path,apical_dendrite_emd_with_basal_dendrite,apical_dendrite_extent_x,apical_dendrite_extent_y,...,basal_dendrite_soma_percentile_y,basal_dendrite_stem_exit_down,basal_dendrite_stem_exit_side,basal_dendrite_stem_exit_up,basal_dendrite_total_length,basal_dendrite_total_surface_area,soma_aligned_dist_from_pia,project_id,feature_set_id,id
0,147.076721,388.737332,-0.134846,-7.323705,-16.315251,2.834573,0.377581,63.287174,303.832247,430.002777,...,0.859339,0.000000,1.000000,0.000000,1842.712482,4251.727723,543.539902,visp_exc_patchseq,exc_visp_morph_features,601628311
1,117.918472,513.295648,181.612081,-49.761568,75.880212,18.681380,0.272368,49.580831,323.203125,680.002141,...,0.894992,0.000000,1.000000,0.000000,1559.948300,3349.079209,541.661529,visp_exc_patchseq,exc_visp_morph_features,603229579
2,74.871318,382.301002,-77.738239,-19.625268,-50.744753,-86.666445,0.384813,13.400124,254.446243,446.575015,...,0.305389,0.250000,0.500000,0.250000,1467.914882,2933.822544,458.134219,visp_exc_patchseq,exc_visp_morph_features,603337985
3,130.585618,424.042586,309.580620,-48.441029,104.774864,-43.013513,0.370210,45.136786,355.122409,644.199169,...,0.840821,0.000000,0.833333,0.166667,2744.146833,7285.432249,498.644308,visp_exc_patchseq,exc_visp_morph_features,603481505
4,15.832649,472.387609,-14.175712,70.002755,-47.532825,-23.029360,0.430200,58.767808,185.047517,501.410723,...,0.697552,0.000000,1.000000,0.000000,3741.880551,12434.022965,467.544831,visp_exc_patchseq,exc_visp_morph_features,603511210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,27.566970,426.478646,-89.878750,-42.625012,7.690337,-8.018195,0.301818,44.870007,171.156424,508.423961,...,0.453674,0.000094,0.999812,0.001988,1088.549274,NaN,896.101355,visp_exc_wnm,exc_visp_morph_features,220308_8021-X22273-Y14515_reg
342,28.460744,511.616625,-29.732973,-44.856429,68.863926,-11.209417,0.438712,29.809223,305.753978,712.083170,...,0.763099,0.000094,0.999812,0.001988,2761.256656,NaN,606.551544,visp_exc_wnm,exc_visp_morph_features,220309_5824-X3486-Y10261_reg
343,2.705247,246.234974,54.324096,19.109618,-88.036493,45.803957,0.540375,27.151869,254.576710,307.956904,...,0.306175,0.173165,0.833121,0.001988,2497.913181,NaN,273.802444,visp_exc_wnm,exc_visp_morph_features,220309_6744-X9496-Y18547_reg
344,38.164678,225.254902,-64.358903,-11.938175,-25.288155,-58.882341,0.473110,14.331949,250.183733,479.609711,...,0.848069,0.000094,0.999812,0.001988,1535.059609,NaN,404.821656,visp_exc_wnm,exc_visp_morph_features,220315_6442-X7542-Y17434_reg
345,103.908356,-309.112977,-151.097797,-17.439567,-27.470389,41.073934,0.424888,28.550967,226.642119,352.985678,...,0.312181,0.259700,0.499740,0.210169,3945.853889,NaN,713.528840,visp_exc_wnm,exc_visp_morph_features,221686_5481-X4093-Y13144_reg

In [36]:
# go through and cast the types of each column according to the cell feature definitions
for cfd in ft_defs:
    col = cfd.id
    df[col] = df[col].astype(np.dtype(cfd.data_type))

In [37]:
table = pa.Table.from_pandas(df, schema=schema, preserve_index=False)

In [38]:
PATH = "../results/cellfeatures/exc_morph_features/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id", "feature_set_id"])

In [39]:
feat_df = pl.read_delta(PATH)

In [40]:
feat_df

shape: (734, 53)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ apical_de ┆ apical_de ┆ apical_de ┆ … ┆ basal_den ┆ soma_alig ┆ project_i ┆ feature_ │
│ ---       ┆ ndrite_bi ┆ ndrite_bi ┆ ndrite_de ┆   ┆ drite_tot ┆ ned_dist_ ┆ d         ┆ set_id   │
│ str       ┆ as_x      ┆ as_y      ┆ pth_pc_0  ┆   ┆ al_surfac ┆ from_pia  ┆ ---       ┆ ---      │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e_a…      ┆ ---       ┆ str       ┆ str      │
│           ┆ f32       ┆ f32       ┆ f32       ┆   ┆ ---       ┆ f32       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 601628311 ┆ 147.07672 ┆ 388.73733 ┆ -0.134846 ┆ … ┆ 4251.7275 ┆ 543.53991 ┆ visp_exc_ ┆ exc_visp │
│           ┆ 1         ┆ 5         ┆           ┆   ┆ 39        ┆ 7         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 603229579 ┆ 117.91847 ┆ 513.29565 ┆ 181.61207 ┆ … ┆ 3349.0791 ┆ 541.66149 ┆ visp_exc_ ┆ exc_visp │
│           ┆ 2         ┆ 4         ┆ 6         ┆   ┆ 02        ┆ 9         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 603337985 ┆ 74.871315 ┆ 382.30099 ┆ -77.73823 ┆ … ┆ 2933.8225 ┆ 458.13421 ┆ visp_exc_ ┆ exc_visp │
│           ┆           ┆ 5         ┆ 5         ┆   ┆ 1         ┆ 6         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 603481505 ┆ 130.58561 ┆ 424.04257 ┆ 309.58062 ┆ … ┆ 7285.4321 ┆ 498.64431 ┆ visp_exc_ ┆ exc_visp │
│           ┆ 7         ┆ 2         ┆ 7         ┆   ┆ 29        ┆ 8         ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ 603511210 ┆ 15.832649 ┆ 472.38760 ┆ -14.17571 ┆ … ┆ 12434.023 ┆ 467.54483 ┆ visp_exc_ ┆ exc_visp │
│           ┆           ┆ 4         ┆ 2         ┆   ┆ 438       ┆           ┆ patchseq  ┆ _morph_f │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 220308_80 ┆ 27.566971 ┆ 426.47863 ┆ -89.87875 ┆ … ┆ null      ┆ 896.10137 ┆ visp_exc_ ┆ exc_visp │
│ 21-X22273 ┆           ┆ 8         ┆ 4         ┆   ┆           ┆ 9         ┆ wnm       ┆ _morph_f │
│ -Y14515_r ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ eg        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 220309_58 ┆ 28.460745 ┆ 511.61663 ┆ -29.73297 ┆ … ┆ null      ┆ 606.55151 ┆ visp_exc_ ┆ exc_visp │
│ 24-X3486- ┆           ┆ 8         ┆ 3         ┆   ┆           ┆ 4         ┆ wnm       ┆ _morph_f │
│ Y10261_re ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ g         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 220309_67 ┆ 2.705247  ┆ 246.23497 ┆ 54.324097 ┆ … ┆ null      ┆ 273.80242 ┆ visp_exc_ ┆ exc_visp │
│ 44-X9496- ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆ wnm       ┆ _morph_f │
│ Y18547_re ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ g         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 220315_64 ┆ 38.164677 ┆ 225.25489 ┆ -64.35890 ┆ … ┆ null      ┆ 404.82165 ┆ visp_exc_ ┆ exc_visp │
│ 42-X7542- ┆           ┆ 8         ┆ 2         ┆   ┆           ┆ 5         ┆ wnm       ┆ _morph_f │
│ Y17434_re ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ g         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 221686_54 ┆ 103.90835 ┆ -309.1129 ┆ -151.0977 ┆ … ┆ null      ┆ 713.52887 ┆ visp_exc_ ┆ exc_visp │
│ 81-X4093- ┆ 6         ┆ 76        ┆ 94        ┆   ┆           ┆           ┆ wnm       ┆ _morph_f │
│ Y13144_re ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eatures  │
│ g         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘