In [1]:
import os
import sys
import numpy as np
import pandas as pd
import seaborn as sns
import pyarrow as pa
import polars as pl
from matplotlib import pyplot as plt
from deltalake import DeltaTable, write_deltalake

In [2]:
sys.path.append(str("/root/capsule/src/"))

In [3]:
from connects_common_connectivity.arrow_utils import build_arrow_schema, models_to_table, attach_linkml_metadata
from connects_common_connectivity.models import DataSet, Modality, DataItem, DataItemDataSetAssociation

# Reference Tasic 2018 data set

In [4]:
tasic_2018_ds = DataSet(
    id="tasic_2018_visp_scrnaseq",
    name="Tasic et al. 2018 VISp RNA-seq data set",
    publication="doi.org/10.1038/s41586-018-0654-5",
    modality=Modality.OTHER.value,
    project_id="tasic_visp_scrnaseq",
)

In [5]:
schema = build_arrow_schema(DataSet)
table = models_to_table([tasic_2018_ds], schema)
table = attach_linkml_metadata(table, linkml_class="DataSet")

In [6]:
PATH = "../results/dataset/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

# Inhibitory Patch-seq data set

In [7]:
Modality.MORPHOLOGY.value

'MORPHOLOGY'

In [8]:
inh_ps_ds = DataSet(
    id="visp_inh_patchseq",
    name="VISp inhibitory Patch-seq data set",
    publication="doi.org/10.1016/j.cell.2020.09.057",
    modality=Modality.MORPHOLOGY.value,
    project_id="visp_patchseq",
)

In [9]:
schema = build_arrow_schema(DataSet)
table = models_to_table([inh_ps_ds], schema)
table = attach_linkml_metadata(table, linkml_class="DataSet")

In [10]:
PATH = "../results/dataset/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

In [11]:
inh_ps_df = pd.read_csv("../data/visp-features-and-mapping/patchseq_tx_cell_ttype_labels.csv", index_col=0)

In [12]:
data_items = []
data_set_data_item_assoc = []
for i, r in inh_ps_df.iterrows():
    data_items.append(DataItem(
        id=str(i),
        name=str(i),
        project_id="visp_patchseq",
    ))
    data_set_data_item_assoc.append(DataItemDataSetAssociation(
        dataitem_id=str(i),
        dataset_id=inh_ps_ds.id,
        project_id='visp_patchseq'
    ))

In [13]:
schema = build_arrow_schema(DataItem)
table = models_to_table(data_items, schema)
table = attach_linkml_metadata(table, linkml_class="DataItem")  # version auto-populated

In [14]:
PATH = "../results/dataitem/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

In [15]:
schema = build_arrow_schema(DataItemDataSetAssociation)
table = models_to_table(data_set_data_item_assoc, schema)
table = attach_linkml_metadata(table, linkml_class="DataItemDataSetAssociation")  # version auto-populated

In [16]:
PATH = "../results/dataitem_dataset_association/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

# Excitatory Patch-seq data set

In [17]:
exc_ps_ds = DataSet(
    id="visp_exc_patchseq",
    name="VISp excitatory Patch-seq data set",
    publication="doi.org/10.1101/2023.11.25.568393",
    modality=Modality.MORPHOLOGY.value,
    project_id="visp_patchseq",
)

In [18]:
schema = build_arrow_schema(DataSet)
table = models_to_table([exc_ps_ds], schema)
table = attach_linkml_metadata(table, linkml_class="DataSet")

In [19]:
PATH = "../results/dataset/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

In [20]:
exc_ps_df = pd.read_csv("../data/visp-features-and-mapping/inferred_met_types.csv", index_col=0)

In [21]:
data_items = []
data_set_data_item_assoc = []
for i, r in exc_ps_df.iterrows():
    data_items.append(DataItem(
        id=str(i),
        name=str(i),
        project_id="visp_patchseq",
    ))
    data_set_data_item_assoc.append(DataItemDataSetAssociation(
        dataitem_id=str(i),
        dataset_id=exc_ps_ds.id,
        project_id='visp_patchseq'
    ))

In [22]:
schema = build_arrow_schema(DataItem)
table = models_to_table(data_items, schema)
table = attach_linkml_metadata(table, linkml_class="DataItem")  # version auto-populated

In [23]:
PATH = "../results/dataitem/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

In [24]:
schema = build_arrow_schema(DataItemDataSetAssociation)
table = models_to_table(data_set_data_item_assoc, schema)
table = attach_linkml_metadata(table, linkml_class="DataItemDataSetAssociation")  # version auto-populated

In [25]:
PATH = "../results/dataitem_dataset_association/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

# Excitatory WNM data set

In [26]:
exc_wnm_ds = DataSet(
    id="visp_exc_wnm",
    name="VISp excitatory whole neuron morphology data set",
    publication="doi.org/10.1101/2023.11.25.568393",
    modality=Modality.MORPHOLOGY.value,
    project_id="visp_wnm",
)

In [27]:
schema = build_arrow_schema(DataSet)
table = models_to_table([exc_wnm_ds], schema)
table = attach_linkml_metadata(table, linkml_class="DataSet")

In [28]:
PATH = "../results/dataset/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

In [29]:
exc_wnm_df = pd.read_csv("../data/visp-features-and-mapping/FullMorphMetaData_Master.csv", index_col=0)

In [30]:
exc_wnm_df["id"] = [i[:-4] for i in exc_wnm_df.index]

In [31]:
data_items = []
data_set_data_item_assoc = []
for i, r in exc_wnm_df.iterrows():
    data_items.append(DataItem(
        id=str(r.id),
        name=str(r.id),
        project_id="visp_wnm",
    ))
    data_set_data_item_assoc.append(DataItemDataSetAssociation(
        dataitem_id=str(r.id),
        dataset_id=exc_wnm_ds.id,
        project_id='visp_wnm'
    ))

In [32]:
schema = build_arrow_schema(DataItem)
table = models_to_table(data_items, schema)
table = attach_linkml_metadata(table, linkml_class="DataItem")  # version auto-populated

In [33]:
PATH = "../results/dataitem/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

In [34]:
schema = build_arrow_schema(DataItemDataSetAssociation)
table = models_to_table(data_set_data_item_assoc, schema)
table = attach_linkml_metadata(table, linkml_class="DataItemDataSetAssociation")  # version auto-populated

In [35]:
PATH = "../results/dataitem_dataset_association/"
write_deltalake(PATH, table, mode="append", partition_by=["project_id"])

# Test reading back (as data frames)

In [36]:
data_items_df = pl.read_delta("../results/dataitem/")

In [37]:
data_items_df

shape: (4_628, 4)
┌──────────────────────────────┬──────────────────────────────┬───────────────────┬───────────────┐
│ id                           ┆ name                         ┆ neuroglancer_link ┆ project_id    │
│ ---                          ┆ ---                          ┆ ---               ┆ ---           │
│ str                          ┆ str                          ┆ str               ┆ str           │
╞══════════════════════════════╪══════════════════════════════╪═══════════════════╪═══════════════╡
│ 182709_6984-X2452-Y12423_reg ┆ 182709_6984-X2452-Y12423_reg ┆ null              ┆ visp_wnm      │
│ 182709_7126-X2913-Y10535_reg ┆ 182709_7126-X2913-Y10535_reg ┆ null              ┆ visp_wnm      │
│ 182724_5937-X3804-Y11955_reg ┆ 182724_5937-X3804-Y11955_reg ┆ null              ┆ visp_wnm      │
│ 182724_6175-X3782-Y10859_reg ┆ 182724_6175-X3782-Y10859_reg ┆ null              ┆ visp_wnm      │
│ 182724_6354-X4834-Y8105_reg  ┆ 182724_6354-X4834-Y8105_reg  ┆ null              ┆ visp_wnm      │
│ …                            ┆ …                            ┆ …                 ┆ …             │
│ 700357513                    ┆ 700357513                    ┆ null              ┆ visp_patchseq │
│ 711511692                    ┆ 711511692                    ┆ null              ┆ visp_patchseq │
│ 652809932                    ┆ 652809932                    ┆ null              ┆ visp_patchseq │
│ 738925092                    ┆ 738925092                    ┆ null              ┆ visp_patchseq │
│ 772422057                    ┆ 772422057                    ┆ null              ┆ visp_patchseq │
└──────────────────────────────┴──────────────────────────────┴───────────────────┴───────────────┘

In [38]:
di_ds_assoc_df = pl.read_delta("../results/dataitem_dataset_association/")

In [39]:
di_ds_assoc_df

shape: (4_628, 3)
┌──────────────────────────────┬───────────────────┬───────────────┐
│ dataitem_id                  ┆ dataset_id        ┆ project_id    │
│ ---                          ┆ ---               ┆ ---           │
│ str                          ┆ str               ┆ str           │
╞══════════════════════════════╪═══════════════════╪═══════════════╡
│ 182709_6984-X2452-Y12423_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182709_7126-X2913-Y10535_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182724_5937-X3804-Y11955_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182724_6175-X3782-Y10859_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182724_6354-X4834-Y8105_reg  ┆ visp_exc_wnm      ┆ visp_wnm      │
│ …                            ┆ …                 ┆ …             │
│ 700357513                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 711511692                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 652809932                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 738925092                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 772422057                    ┆ visp_inh_patchseq ┆ visp_patchseq │
└──────────────────────────────┴───────────────────┴───────────────┘