# Combine microns1412 and visp_deltalakes into a single Delta Lake dataset

Auto-discovers all delta tables in both source datasets by scanning for `_delta_log/` directories,
then writes a unified combined dataset to `/scratch/combined_datasets/`.

- Tables that exist at the same relative path in both sources are concatenated.
- Tables unique to one source are copied through as-is.
- Nested sub-tables (e.g. `cellfeatures/csm_cluster_features`) remain independent.

In [1]:
import os

import pyarrow as pa
import polars as pl
from deltalake import DeltaTable, write_deltalake

In [2]:
CODEOCEAN_MICRONS = "/data/microns1412"
CODEOCEAN_VISP = "/data/visp_deltalakes"
LOCAL_MICRONS = "../data/microns1412"
LOCAL_VISP = "../data/visp_deltalakes"

MICRONS_ROOT = CODEOCEAN_MICRONS if os.path.exists(CODEOCEAN_MICRONS) else LOCAL_MICRONS
VISP_ROOT = CODEOCEAN_VISP if os.path.exists(CODEOCEAN_VISP) else LOCAL_VISP

OUTPUT_ROOT = "/scratch/combined_datasets"

print(f"Microns root: {MICRONS_ROOT}")
print(f"VISP root:    {VISP_ROOT}")
print(f"Output root:  {OUTPUT_ROOT}")

Microns root: /data/microns1412
VISP root:    /data/visp_deltalakes
Output root:  /scratch/combined_datasets

In [ ]:
def discover_delta_tables(root: str) -> dict[str, str]:
    """
    Walk *root* and return {relative_table_path: absolute_table_path}
    for every directory that contains a `_delta_log/` subdirectory.
    """
    root = os.path.abspath(root)
    tables = {}
    for dirpath, dirnames, _ in os.walk(root):
        if "_delta_log" in dirnames:
            rel = os.path.relpath(dirpath, root)
            tables[rel] = dirpath
            dirnames.remove("_delta_log")
    return tables

In [4]:
microns_tables = discover_delta_tables(MICRONS_ROOT)
visp_tables = discover_delta_tables(VISP_ROOT)

all_rel_paths = sorted(set(microns_tables) | set(visp_tables))

table_sources: dict[str, list[str]] = {}
for rel in all_rel_paths:
    sources = []
    if rel in microns_tables:
        sources.append(microns_tables[rel])
    if rel in visp_tables:
        sources.append(visp_tables[rel])
    table_sources[rel] = sources

print(f"Discovered {len(all_rel_paths)} delta tables:\n")
for rel, srcs in table_sources.items():
    labels = []
    if rel in microns_tables:
        labels.append("microns")
    if rel in visp_tables:
        labels.append("visp")
    print(f"  {rel:50s}  [{', '.join(labels)}]")

Discovered 20 delta tables:

  .Trash-0/files/minnie65_std_transform_coordinates   [microns]
  cellcellconnectivitylong                            [microns]
  cellfeaturedefinition                               [microns]
  cellfeaturedefinition/visp_exc                      [visp]
  cellfeaturedefinition/visp_inh                      [visp]
  cellfeatures/csm_cluster_features                   [microns]
  cellfeatures/csm_cluster_features_umap              [microns]
  cellfeatures/exc_morph_features                     [visp]
  cellfeatures/inh_morph_features                     [visp]
  cellfeatures/minnie65_std_transform_coordinates     [microns]
  cellfeatureset                                      [microns]
  cellfeatureset/visp_exc                             [visp]
  cellfeatureset/visp_inh                             [visp]
  celltoclustermapping                                [visp]
  cluster                                             [microns, visp]
  clustermembership                                   [microns, visp]
  dataitem                                            [microns, visp]
  dataitem_dataset_association                        [microns, visp]
  dataset                                             [microns, visp]
  mappingset                                          [visp]

In [5]:
def combine_and_write(rel_path: str, source_paths: list[str], output_root: str) -> int:
    """
    Read delta table(s) from *source_paths*, concatenate if more than one,
    and write a fresh delta table to output_root/rel_path.

    Returns total row count of the combined table.
    """
    tables = []
    partition_cols: list[str] = []

    for src in source_paths:
        dt = DeltaTable(src)
        part_cols = dt.metadata().partition_columns
        if part_cols:
            partition_cols = part_cols
        tables.append(dt.to_pyarrow_table())

    if len(tables) == 1:
        combined = tables[0]
    else:
        combined = pa.concat_tables(tables, promote_options="permissive")

    out_path = os.path.join(output_root, rel_path)
    os.makedirs(out_path, exist_ok=True)

    write_kwargs = dict(mode="overwrite")
    if partition_cols:
        write_kwargs["partition_by"] = partition_cols

    write_deltalake(out_path, combined, **write_kwargs)
    return combined.num_rows

In [6]:
os.makedirs(OUTPUT_ROOT, exist_ok=True)

for rel_path, source_paths in table_sources.items():
    n_sources = len(source_paths)
    action = "merging" if n_sources > 1 else "copying"
    print(f"{action:8s} {rel_path} ({n_sources} source{'s' if n_sources > 1 else ''}) ... ", end="", flush=True)
    nrows = combine_and_write(rel_path, source_paths, OUTPUT_ROOT)
    print(f"{nrows:,} rows")

print("\nDone.")

copying  .Trash-0/files/minnie65_std_transform_coordinates (1 source) ... 133,969 rows
copying  cellcellconnectivitylong (1 source) ... 1,592,196 rows
copying  cellfeaturedefinition (1 source) ... 87 rows
copying  cellfeaturedefinition/visp_exc (1 source) ... 50 rows
copying  cellfeaturedefinition/visp_inh (1 source) ... 46 rows
copying  cellfeatures/csm_cluster_features (1 source) ... 35,787 rows
copying  cellfeatures/csm_cluster_features_umap (1 source) ... 35,787 rows
copying  cellfeatures/exc_morph_features (1 source) ... 734 rows
copying  cellfeatures/inh_morph_features (1 source) ... 520 rows
copying  cellfeatures/minnie65_std_transform_coordinates (1 source) ... 133,969 rows
copying  cellfeatureset (1 source) ... 3 rows
copying  cellfeatureset/visp_exc (1 source) ... 1 rows
copying  cellfeatureset/visp_inh (1 source) ... 1 rows
copying  celltoclustermapping (1 source) ... 18,171 rows
merging  cluster (2 sources) ... 202 rows
merging  clustermembership (2 sources) ... 109,977 rows
merging  dataitem (2 sources) ... 138,597 rows
merging  dataitem_dataset_association (2 sources) ... 42,377 rows
merging  dataset (2 sources) ... 6 rows
copying  mappingset (1 source) ... 1 rows

Done.

## Verification

Read back the combined tables and print shapes to confirm everything was written correctly.

In [7]:
print(f"{'Table':<50s} {'Rows':>10s} {'Cols':>6s}")
print("-" * 68)

for rel_path in sorted(table_sources):
    out_path = os.path.join(OUTPUT_ROOT, rel_path)
    df = pl.read_delta(out_path)
    print(f"{rel_path:<50s} {df.shape[0]:>10,d} {df.shape[1]:>6d}")

Table                                                    Rows   Cols
--------------------------------------------------------------------
.Trash-0/files/minnie65_std_transform_coordinates     133,969      6
cellcellconnectivitylong                            1,592,196      9
cellfeaturedefinition                                      87      6
cellfeaturedefinition/visp_exc                             50      6
cellfeaturedefinition/visp_inh                             46      6
cellfeatures/csm_cluster_features                      35,787     85
cellfeatures/csm_cluster_features_umap                 35,787      5
cellfeatures/exc_morph_features                           734     53
cellfeatures/inh_morph_features                           520     49
cellfeatures/minnie65_std_transform_coordinates       133,969      6
cellfeatureset                                              3      4
cellfeatureset/visp_exc                                     1      4
cellfeatureset/visp_inh                                     1      4
celltoclustermapping                                   18,171      8
cluster                                                   202      9
clustermembership                                     109,977      6
dataitem                                              138,597      4
dataitem_dataset_association                           42,377      3
dataset                                                     6      5
mappingset                                                  1     11

In [3]:
print("Sample: combined dataset table")
pl.read_delta(os.path.join(OUTPUT_ROOT, "dataset"))

Sample: combined dataset table

shape: (6, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ id                ┆ name              ┆ publication       ┆ modality          ┆ project_id       │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ str               ┆ str               ┆ str               ┆ str               ┆ str              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ visp_exc_wnm      ┆ VISp excitatory   ┆ doi.org/10.1101/2 ┆ MORPHOLOGY        ┆ visp_wnm         │
│                   ┆ whole neuron m…   ┆ 023.11.25.568…    ┆                   ┆                  │
│ minnie65_v1412_cs ┆ Minnie65 v1412    ┆ none              ┆ ELECTRON_MICROSCO ┆ minnie65         │
│ m_cluster         ┆ CSM Dendrite Ul…  ┆                   ┆ PY                ┆                  │
│ minnie65_v1412_pr ┆ Minnie65 v1412    ┆ none              ┆ ELECTRON_MICROSCO ┆ minnie65         │
│ oofread           ┆ Cells With Proo…  ┆                   ┆ PY                ┆                  │
│ visp_exc_patchseq ┆ VISp excitatory   ┆ doi.org/10.1101/2 ┆ MORPHOLOGY        ┆ visp_patchseq    │
│                   ┆ Patch-seq data…   ┆ 023.11.25.568…    ┆                   ┆                  │
│ visp_inh_patchseq ┆ VISp inhibitory   ┆ doi.org/10.1016/j ┆ MORPHOLOGY        ┆ visp_patchseq    │
│                   ┆ Patch-seq data…   ┆ .cell.2020.09…    ┆                   ┆                  │
│ tasic_2018_visp_s ┆ Tasic et al. 2018 ┆ doi.org/10.1038/s ┆ OTHER             ┆ tasic_visp_scrna │
│ crnaseq           ┆ VISp RNA-seq…     ┆ 41586-018-065…    ┆                   ┆ seq              │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [12]:
df = pl.read_delta(os.path.join(OUTPUT_ROOT, "dataitem_dataset_association"))
print(f"Unique project_ids: {df['project_id'].unique().to_list()}")
print(f"Unique dataset_ids: {df['dataset_id'].unique().to_list()}")
df

Unique project_ids: ['visp_wnm', 'minnie65', 'visp_patchseq']
Unique dataset_ids: ['minnie65_v1412_csm_cluster', 'visp_inh_patchseq', 'visp_exc_patchseq', 'minnie65_v1412_proofread', 'visp_exc_wnm']

shape: (42_377, 3)
┌──────────────────────────────┬───────────────────┬───────────────┐
│ dataitem_id                  ┆ dataset_id        ┆ project_id    │
│ ---                          ┆ ---               ┆ ---           │
│ str                          ┆ str               ┆ str           │
╞══════════════════════════════╪═══════════════════╪═══════════════╡
│ 182709_6984-X2452-Y12423_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182709_7126-X2913-Y10535_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182724_5937-X3804-Y11955_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182724_6175-X3782-Y10859_reg ┆ visp_exc_wnm      ┆ visp_wnm      │
│ 182724_6354-X4834-Y8105_reg  ┆ visp_exc_wnm      ┆ visp_wnm      │
│ …                            ┆ …                 ┆ …             │
│ 700357513                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 711511692                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 652809932                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 738925092                    ┆ visp_inh_patchseq ┆ visp_patchseq │
│ 772422057                    ┆ visp_inh_patchseq ┆ visp_patchseq │
└──────────────────────────────┴───────────────────┴───────────────┘

In [6]:
print("Sample: combined cluster table")
df = pl.read_delta(os.path.join(OUTPUT_ROOT, "cluster"))
print(f"Unique project_ids: {df['project_id'].unique().to_list()}")
df

Sample: combined cluster table
Unique project_ids: ['visp_met_types', 'tasic_2018_visp_scrnaseq', 'minnie65']

shape: (202, 9)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ parent     ┆ children   ┆ level ┆ … ┆ hex_color ┆ heirachy_ ┆ distance_ ┆ project_i │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ category  ┆ to_parent ┆ d         │
│ str        ┆ str        ┆ list[str]  ┆ i64   ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆ f64       ┆ str       │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ cell       ┆ null       ┆ ["GABAergi ┆ 0     ┆ … ┆ #000000   ┆ major_cla ┆ null      ┆ tasic_201 │
│            ┆            ┆ c", "Gluta ┆       ┆   ┆           ┆ ss        ┆           ┆ 8_visp_sc │
│            ┆            ┆ matergic", ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│            ┆            ┆ …          ┆       ┆   ┆           ┆           ┆           ┆           │
│ GABAergic  ┆ cell       ┆ ["Pvalb",  ┆ 1     ┆ … ┆ #EF4136   ┆ class     ┆ null      ┆ tasic_201 │
│            ┆            ┆ "Vip", …   ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ "Meis2"]   ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│ Glutamater ┆ cell       ┆ ["L4",     ┆ 1     ┆ … ┆ #27AAE1   ┆ class     ┆ null      ┆ tasic_201 │
│ gic        ┆            ┆ "L2/3 IT", ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ … "CR"]    ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│ Non-Neuron ┆ cell       ┆ ["Oligo",  ┆ 1     ┆ … ┆ #8D1800   ┆ class     ┆ null      ┆ tasic_201 │
│ al         ┆            ┆ "Astro", … ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ "SMC"]     ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│ Pvalb      ┆ GABAergic  ┆ ["Pvalb    ┆ 2     ┆ … ┆ #D93137   ┆ subclass  ┆ null      ┆ tasic_201 │
│            ┆            ┆ Tpbg",     ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ "Pvalb     ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│            ┆            ┆ Reln Itm…  ┆       ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ L5IT       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #b76969   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L6IT       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #7d354c   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L5ET       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #c68076   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L5NP       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #a6565f   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L6SP       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #663333   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
print("Sample: combined dataitem table")
df = pl.read_delta(os.path.join(OUTPUT_ROOT, "dataitem"))
print(f"Unique project_ids: {df['project_id'].unique().to_list()}")
df

Sample: combined dataitem table
Unique project_ids: ['minnie65', 'visp_wnm', 'visp_patchseq']

shape: (138_597, 4)
┌───────────┬────────────────────┬───────────────────┬───────────────┐
│ id        ┆ name               ┆ neuroglancer_link ┆ project_id    │
│ ---       ┆ ---                ┆ ---               ┆ ---           │
│ str       ┆ str                ┆ str               ┆ str           │
╞═══════════╪════════════════════╪═══════════════════╪═══════════════╡
│ 373879    ┆ 864691136090135607 ┆ null              ┆ minnie65      │
│ 201858    ┆ 864691135373893678 ┆ null              ┆ minnie65      │
│ 600774    ┆ 864691135682378744 ┆ null              ┆ minnie65      │
│ 408486    ┆ 864691135194387242 ┆ null              ┆ minnie65      │
│ 598774    ┆ 864691135741608653 ┆ null              ┆ minnie65      │
│ …         ┆ …                  ┆ …                 ┆ …             │
│ 700357513 ┆ 700357513          ┆ null              ┆ visp_patchseq │
│ 711511692 ┆ 711511692          ┆ null              ┆ visp_patchseq │
│ 652809932 ┆ 652809932          ┆ null              ┆ visp_patchseq │
│ 738925092 ┆ 738925092          ┆ null              ┆ visp_patchseq │
│ 772422057 ┆ 772422057          ┆ null              ┆ visp_patchseq │
└───────────┴────────────────────┴───────────────────┴───────────────┘

---

# Clusters that were mapped to
__tasic_2018_visp_scrnaseq, visp_met_types, minnie65__

In [14]:
df = pl.read_delta(os.path.join(OUTPUT_ROOT, "cluster"))
print(f"Unique project_ids: {df['project_id'].unique().to_list()}")
df

Unique project_ids: ['minnie65', 'tasic_2018_visp_scrnaseq', 'visp_met_types']

shape: (202, 9)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ parent     ┆ children   ┆ level ┆ … ┆ hex_color ┆ heirachy_ ┆ distance_ ┆ project_i │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ category  ┆ to_parent ┆ d         │
│ str        ┆ str        ┆ list[str]  ┆ i64   ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆ f64       ┆ str       │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ cell       ┆ null       ┆ ["GABAergi ┆ 0     ┆ … ┆ #000000   ┆ major_cla ┆ null      ┆ tasic_201 │
│            ┆            ┆ c", "Gluta ┆       ┆   ┆           ┆ ss        ┆           ┆ 8_visp_sc │
│            ┆            ┆ matergic", ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│            ┆            ┆ …          ┆       ┆   ┆           ┆           ┆           ┆           │
│ GABAergic  ┆ cell       ┆ ["Pvalb",  ┆ 1     ┆ … ┆ #EF4136   ┆ class     ┆ null      ┆ tasic_201 │
│            ┆            ┆ "Vip", …   ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ "Meis2"]   ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│ Glutamater ┆ cell       ┆ ["L4",     ┆ 1     ┆ … ┆ #27AAE1   ┆ class     ┆ null      ┆ tasic_201 │
│ gic        ┆            ┆ "L2/3 IT", ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ … "CR"]    ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│ Non-Neuron ┆ cell       ┆ ["Oligo",  ┆ 1     ┆ … ┆ #8D1800   ┆ class     ┆ null      ┆ tasic_201 │
│ al         ┆            ┆ "Astro", … ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ "SMC"]     ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│ Pvalb      ┆ GABAergic  ┆ ["Pvalb    ┆ 2     ┆ … ┆ #D93137   ┆ subclass  ┆ null      ┆ tasic_201 │
│            ┆            ┆ Tpbg",     ┆       ┆   ┆           ┆           ┆           ┆ 8_visp_sc │
│            ┆            ┆ "Pvalb     ┆       ┆   ┆           ┆           ┆           ┆ rnaseq    │
│            ┆            ┆ Reln Itm…  ┆       ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ L5IT       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #b76969   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L6IT       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #7d354c   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L5ET       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #c68076   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L5NP       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #a6565f   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ L6SP       ┆ glutamater ┆ null       ┆ 2     ┆ … ┆ #663333   ┆ subtype   ┆ null      ┆ minnie65  │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
df_ps = df.filter(pl.col("project_id") == "visp_met_types")
df_ps

shape: (48, 9)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ parent     ┆ children   ┆ level ┆ … ┆ hex_color ┆ heirachy_ ┆ distance_ ┆ project_i │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ category  ┆ to_parent ┆ d         │
│ str        ┆ str        ┆ list[str]  ┆ i64   ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆ f64       ┆ str       │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ cell       ┆ null       ┆ ["GABAergi ┆ 0     ┆ … ┆ #000000   ┆ major_cla ┆ null      ┆ visp_met_ │
│            ┆            ┆ c", "Gluta ┆       ┆   ┆           ┆ ss        ┆           ┆ types     │
│            ┆            ┆ matergic"] ┆       ┆   ┆           ┆           ┆           ┆           │
│ GABAergic  ┆ cell       ┆ ["Sst-MET- ┆ 1     ┆ … ┆ #EF4136   ┆ class     ┆ null      ┆ visp_met_ │
│            ┆            ┆ 1", "Sst-M ┆       ┆   ┆           ┆           ┆           ┆ types     │
│            ┆            ┆ ET-2", …   ┆       ┆   ┆           ┆           ┆           ┆           │
│            ┆            ┆ "…         ┆       ┆   ┆           ┆           ┆           ┆           │
│ Glutamater ┆ cell       ┆ ["L2/3     ┆ 1     ┆ … ┆ #27AAE1   ┆ class     ┆ null      ┆ visp_met_ │
│ gic        ┆            ┆ IT", "L4   ┆       ┆   ┆           ┆           ┆           ┆ types     │
│            ┆            ┆ IT", …     ┆       ┆   ┆           ┆           ┆           ┆           │
│            ┆            ┆ "L6b"]     ┆       ┆   ┆           ┆           ┆           ┆           │
│ Sst-MET-1  ┆ GABAergic  ┆ null       ┆ 2     ┆ … ┆ #b9bb67   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
│ Sst-MET-2  ┆ GABAergic  ┆ null       ┆ 2     ┆ … ┆ #804811   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ L5 ET-3    ┆ Glutamater ┆ null       ┆ 2     ┆ … ┆ #29E043   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
│ L5 NP      ┆ Glutamater ┆ null       ┆ 2     ┆ … ┆ #73CA95   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
│ L6 CT-1    ┆ Glutamater ┆ null       ┆ 2     ┆ … ┆ #74CAFF   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
│ L6 CT-2    ┆ Glutamater ┆ null       ┆ 2     ┆ … ┆ #578EBF   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
│ L6b        ┆ Glutamater ┆ null       ┆ 2     ┆ … ┆ #2B7880   ┆ cluster   ┆ null      ┆ visp_met_ │
│            ┆ gic        ┆            ┆       ┆   ┆           ┆           ┆           ┆ types     │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

# OG Cluster Membership
- __minnie65__ — Has its __own clustering__ (neuron → glutamatergic/gabaergic → subtypes like L4IT, PTC, etc.) under project_id="minnie65". Each cell gets ClusterMembership entries at each hierarchy level.
- __visp_inh_patchseq__ — Has ClusterMembership entries to the __visp_met_types__ taxonomy (MET-type clusters like Sncg-MET-1, etc.).
- __visp_exc_patchseq__ — Also has ClusterMembership entries to __the visp_met_types__ taxonomy.   

__Problem: The "cluster" column will show the children clusters without the cluster_project_id__ but L6b of met types wont be the same as L6b of minnie types

In [9]:
df = pl.read_delta(os.path.join(OUTPUT_ROOT, "clustermembership"))
print(f"Unique project_ids: {df['project_id'].unique().to_list()}")
df

Unique project_ids: ['visp_inh_patchseq', 'minnie65', 'visp_exc_patchseq']

shape: (109_977, 6)
┌────────────┬───────────────┬──────────────────┬─────────────┬──────────┬───────────────────┐
│ item       ┆ cluster       ┆ membership_score ┆ probability ┆ distance ┆ project_id        │
│ ---        ┆ ---           ┆ ---              ┆ ---         ┆ ---      ┆ ---               │
│ str        ┆ str           ┆ f64              ┆ f64         ┆ f64      ┆ str               │
╞════════════╪═══════════════╪══════════════════╪═════════════╪══════════╪═══════════════════╡
│ 1039273993 ┆ L6b           ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 1039273993 ┆ Glutamatergic ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 1039273993 ┆ cell          ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 823218199  ┆ L5 ET-3       ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 823218199  ┆ Glutamatergic ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ …          ┆ …             ┆ …                ┆ …           ┆ …        ┆ …                 │
│ 993245688  ┆ GABAergic     ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993245688  ┆ cell          ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993283588  ┆ Sncg-MET-1    ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993283588  ┆ GABAergic     ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993283588  ┆ cell          ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
└────────────┴───────────────┴──────────────────┴─────────────┴──────────┴───────────────────┘

## Cell to cluster mapping (cross-taxonomy mapping)
- __visp_inh_patchseq__ → mapped to __tasic_2018_visp_scrnaseq__ (T-type mapping via "Tree mapping" method), under __mapping set visp_inh_patchseq_ttype_mapping__.
- __visp_exc_patchseq__ → mapped to __tasic_2018_visp_scrnaseq__ (T-type mapping via "Tree mapping" method), under __mapping set visp_exc_patchseq_ttype_mapping__.
- __visp_exc_wnm__ → mapped to __visp_met_types__ under mapping set __visp_exc_wnm_mettype_mapping__, using "Routed random forest mapping". This includes a probability score per mapping.

In [11]:
df = pl.read_delta(os.path.join(OUTPUT_ROOT, "celltoclustermapping"))
print(f"Unique project_ids: {df['project_id'].unique().to_list()}")
print(f"Unique mapping_sets: {df['mapping_set'].unique().to_list()}")
df

Unique project_ids: ['visp_inh_patchseq', 'visp_exc_wnm', 'visp_exc_patchseq']
Unique mapping_sets: ['visp_exc_wnm_mettype_mapping', 'visp_inh_patchseq_ttype_mapping', 'visp_exc_patchseq_ttype_mapping']

shape: (18_171, 8)
┌─────────────┬─────────────┬─────────────┬─────────────┬───────┬─────────────┬───────┬────────────┐
│ id          ┆ mapping_set ┆ source_cell ┆ target_clus ┆ score ┆ probability ┆ notes ┆ project_id │
│ ---         ┆ ---         ┆ ---         ┆ ter         ┆ ---   ┆ ---         ┆ ---   ┆ ---        │
│ str         ┆ str         ┆ str         ┆ ---         ┆ f64   ┆ f64         ┆ str   ┆ str        │
│             ┆             ┆             ┆ str         ┆       ┆             ┆       ┆            │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══════╪═════════════╪═══════╪════════════╡
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ L5 ET-2     ┆ null  ┆ 0.988       ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆             ┆       ┆             ┆       ┆ nm         │
│ 23_reg-L…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆ ic          ┆       ┆             ┆       ┆ nm         │
│ 23_reg-G…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆             ┆       ┆             ┆       ┆ nm         │
│ 23_reg-c…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_7126 ┆ visp_exc_wn ┆ 182709_7126 ┆ L5 ET-3     ┆ null  ┆ 0.918       ┆ null  ┆ visp_exc_w │
│ -X2913-Y105 ┆ m_mettype_m ┆ -X2913-Y105 ┆             ┆       ┆             ┆       ┆ nm         │
│ 35_reg-L…   ┆ apping      ┆ 35_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_7126 ┆ visp_exc_wn ┆ 182709_7126 ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2913-Y105 ┆ m_mettype_m ┆ -X2913-Y105 ┆ ic          ┆       ┆             ┆       ┆ nm         │
│ 35_reg-G…   ┆ apping      ┆ 35_reg      ┆             ┆       ┆             ┆       ┆            │
│ …           ┆ …           ┆ …           ┆ …           ┆ …     ┆ …           ┆ …     ┆ …          │
│ 645369849-c ┆ visp_exc_pa ┆ 645369849   ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ ell-visp_ex ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ c_patchs…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-L ┆ visp_exc_pa ┆ 831254527   ┆ L6 CT VISp  ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ 6 CT VISp   ┆ tchseq_ttyp ┆             ┆ Ctxn3 Sla   ┆       ┆             ┆       ┆ atchseq    │
│ Ctxn3 Sla…  ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-L ┆ visp_exc_pa ┆ 831254527   ┆ L6 CT       ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ 6 CT-visp_e ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ xc_patch…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-G ┆ visp_exc_pa ┆ 831254527   ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ lutamatergi ┆ tchseq_ttyp ┆             ┆ ic          ┆       ┆             ┆       ┆ atchseq    │
│ c-visp_e…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-c ┆ visp_exc_pa ┆ 831254527   ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ ell-visp_ex ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ c_patchs…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
└─────────────┴─────────────┴─────────────┴─────────────┴───────┴─────────────┴───────┴────────────┘

---