# Add Emily's INH and EXC features to the minnie deltalakes

In [1]:
import os

import pyarrow as pa
import polars as pl
from deltalake import DeltaTable, write_deltalake
import pandas as pd

In [14]:
DATA_ROOT = '/data'
DELTAS = os.path.join(DATA_ROOT, 'microns1412')
FEATS = os.path.join(DATA_ROOT, 'minniephase3-emily_skeleton_keys_features')
VISP = os.path.join(DATA_ROOT, 'visp_deltalakes')

## Check root id matching
different proofread versions so dataitem IDs might not match

In [3]:
df_dataitem = pl.read_delta(os.path.join(DELTAS, 'dataitem'))
df_dataitem.head()

shape: (5, 4)
┌────────┬────────────────────┬───────────────────┬────────────┐
│ id     ┆ name               ┆ neuroglancer_link ┆ project_id │
│ ---    ┆ ---                ┆ ---               ┆ ---        │
│ str    ┆ str                ┆ str               ┆ str        │
╞════════╪════════════════════╪═══════════════════╪════════════╡
│ 373879 ┆ 864691136090135607 ┆ null              ┆ minnie65   │
│ 201858 ┆ 864691135373893678 ┆ null              ┆ minnie65   │
│ 600774 ┆ 864691135682378744 ┆ null              ┆ minnie65   │
│ 408486 ┆ 864691135194387242 ┆ null              ┆ minnie65   │
│ 598774 ┆ 864691135741608653 ┆ null              ┆ minnie65   │
└────────┴────────────────────┴───────────────────┴────────────┘

In [4]:
df_feat_exc = pl.read_csv(os.path.join(FEATS, 'minniephase3-emily_skeleton_keys_features_v661_excitatory_wide_normalized.csv')) 
df_feat_exc.head()

shape: (5, 56)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ specimen_ ┆ apical_de ┆ apical_de ┆ apical_de ┆ … ┆ basal_den ┆ basal_den ┆ soma_alig ┆ soma_sur │
│ id        ┆ ndrite_bi ┆ ndrite_bi ┆ ndrite_de ┆   ┆ drite_tot ┆ drite_tot ┆ ned_dist_ ┆ face_are │
│ ---       ┆ as_x      ┆ as_y      ┆ pth_pc_0  ┆   ┆ al_length ┆ al_surfac ┆ from_pia  ┆ a        │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ e_a…      ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 23141     ┆ -0.04521  ┆ -1.384222 ┆ -0.410158 ┆ … ┆ -1.662646 ┆ -1.441727 ┆ -1.317748 ┆ 0.745332 │
│ 23332     ┆ 0.723369  ┆ -1.090688 ┆ -0.155651 ┆ … ┆ -1.304668 ┆ -1.354976 ┆ -1.300258 ┆ -1.43003 │
│ 23373     ┆ -0.321714 ┆ -1.481655 ┆ -0.421491 ┆ … ┆ -2.110242 ┆ -1.877541 ┆ -1.323333 ┆ -0.59807 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 23382     ┆ -0.075403 ┆ -1.376466 ┆ -0.41668  ┆ … ┆ -2.070377 ┆ -1.866828 ┆ -1.288897 ┆ -0.00081 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ 23385     ┆ -0.200827 ┆ -1.551809 ┆ -0.43701  ┆ … ┆ -2.026767 ┆ -1.8753   ┆ -1.218866 ┆ -1.46077 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df_feat_inh = pl.read_csv(os.path.join(FEATS, 'minniephase3-emily_skeleton_keys_features_inhibitory_slanted_column_features_wide_normalized.csv'))
df_feat_inh.head()

shape: (5, 52)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ specimen_ ┆ axon_bias ┆ axon_bias ┆ axon_dept ┆ … ┆ basal_den ┆ basal_den ┆ basal_den ┆ soma_ali │
│ id        ┆ _x        ┆ _y        ┆ h_pc_0    ┆   ┆ drite_ste ┆ drite_tot ┆ drite_tot ┆ gned_dis │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ m_exit_up ┆ al_length ┆ al_surfac ┆ t_from_p │
│ i64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ e_a…      ┆ ia       │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 252232    ┆ 0.278182  ┆ -0.704644 ┆ -0.514704 ┆ … ┆ -0.055458 ┆ -0.270077 ┆ -1.302811 ┆ -1.77590 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ 255120    ┆ 0.854395  ┆ -0.736089 ┆ -0.384483 ┆ … ┆ -0.055458 ┆ -0.25705  ┆ -0.983592 ┆ -1.65424 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 255129    ┆ -0.490082 ┆ -1.381988 ┆ 0.238187  ┆ … ┆ 0.356622  ┆ -0.104537 ┆ -0.517526 ┆ -1.50443 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ 255137    ┆ 1.064403  ┆ -0.883689 ┆ -0.307255 ┆ … ┆ -0.247762 ┆ -0.229144 ┆ -1.13353  ┆ -1.59072 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 255208    ┆ -0.005684 ┆ -0.958777 ┆ -0.300065 ┆ … ┆ 0.109374  ┆ -0.25627  ┆ -1.270286 ┆ -1.66046 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### subset of EXC that's in dataitems
100%

In [6]:
df_feat_exc_overlap = df_feat_exc.join(df_dataitem, left_on=pl.col("specimen_id").cast(pl.String), right_on='id', how='semi')
df_feat_exc_overlap.head()

shape: (5, 56)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ specimen_ ┆ apical_de ┆ apical_de ┆ apical_de ┆ … ┆ basal_den ┆ basal_den ┆ soma_alig ┆ soma_sur │
│ id        ┆ ndrite_bi ┆ ndrite_bi ┆ ndrite_de ┆   ┆ drite_tot ┆ drite_tot ┆ ned_dist_ ┆ face_are │
│ ---       ┆ as_x      ┆ as_y      ┆ pth_pc_0  ┆   ┆ al_length ┆ al_surfac ┆ from_pia  ┆ a        │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ e_a…      ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 23141     ┆ -0.04521  ┆ -1.384222 ┆ -0.410158 ┆ … ┆ -1.662646 ┆ -1.441727 ┆ -1.317748 ┆ 0.745332 │
│ 23332     ┆ 0.723369  ┆ -1.090688 ┆ -0.155651 ┆ … ┆ -1.304668 ┆ -1.354976 ┆ -1.300258 ┆ -1.43003 │
│ 23373     ┆ -0.321714 ┆ -1.481655 ┆ -0.421491 ┆ … ┆ -2.110242 ┆ -1.877541 ┆ -1.323333 ┆ -0.59807 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 23382     ┆ -0.075403 ┆ -1.376466 ┆ -0.41668  ┆ … ┆ -2.070377 ┆ -1.866828 ┆ -1.288897 ┆ -0.00081 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ 23385     ┆ -0.200827 ┆ -1.551809 ┆ -0.43701  ┆ … ┆ -2.026767 ┆ -1.8753   ┆ -1.218866 ┆ -1.46077 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
print(df_feat_exc_overlap.height - df_feat_exc.height)
print(df_feat_exc_overlap.height / df_feat_exc.height)

0
1.0

### subset of INH that's in dataitems
100%

In [8]:
df_feat_inh_overlap = df_feat_inh.join(df_dataitem, left_on=pl.col("specimen_id").cast(pl.String), right_on='id', how='semi')
df_feat_inh_overlap.head()

shape: (5, 52)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ specimen_ ┆ axon_bias ┆ axon_bias ┆ axon_dept ┆ … ┆ basal_den ┆ basal_den ┆ basal_den ┆ soma_ali │
│ id        ┆ _x        ┆ _y        ┆ h_pc_0    ┆   ┆ drite_ste ┆ drite_tot ┆ drite_tot ┆ gned_dis │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ m_exit_up ┆ al_length ┆ al_surfac ┆ t_from_p │
│ i64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ e_a…      ┆ ia       │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 252232    ┆ 0.278182  ┆ -0.704644 ┆ -0.514704 ┆ … ┆ -0.055458 ┆ -0.270077 ┆ -1.302811 ┆ -1.77590 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ 255120    ┆ 0.854395  ┆ -0.736089 ┆ -0.384483 ┆ … ┆ -0.055458 ┆ -0.25705  ┆ -0.983592 ┆ -1.65424 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 255129    ┆ -0.490082 ┆ -1.381988 ┆ 0.238187  ┆ … ┆ 0.356622  ┆ -0.104537 ┆ -0.517526 ┆ -1.50443 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ 255137    ┆ 1.064403  ┆ -0.883689 ┆ -0.307255 ┆ … ┆ -0.247762 ┆ -0.229144 ┆ -1.13353  ┆ -1.59072 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 255208    ┆ -0.005684 ┆ -0.958777 ┆ -0.300065 ┆ … ┆ 0.109374  ┆ -0.25627  ┆ -1.270286 ┆ -1.66046 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
print(df_feat_inh_overlap.height - df_feat_inh.height)
print(df_feat_inh_overlap.height / df_feat_inh.height)

0
1.0

### total in dataitems vs EXC+INH

In [10]:
print(df_dataitem.height)
print(df_feat_exc.height)
print(df_feat_inh.height)

133969
49714
163

### sanity check the cell types and total vs feature-having cells

## Check existing EM features and featuresets

### CELLS X FEATURES per featureset file

In [11]:
df_cellfeatures = pl.read_delta(os.path.join(DELTAS, 'cellfeatures/csm_cluster_features_umap'))
df_cellfeatures.head()

shape: (5, 5)
┌────────┬───────────┬───────────┬────────────┬───────────────────────────┐
│ id     ┆ x_umap    ┆ y_umap    ┆ project_id ┆ feature_set_id            │
│ ---    ┆ ---       ┆ ---       ┆ ---        ┆ ---                       │
│ str    ┆ f32       ┆ f32       ┆ str        ┆ str                       │
╞════════╪═══════════╪═══════════╪════════════╪═══════════════════════════╡
│ 485509 ┆ -0.17924  ┆ 15.240355 ┆ minnie65   ┆ csm_cluster_features_umap │
│ 263203 ┆ -1.704662 ┆ 5.673036  ┆ minnie65   ┆ csm_cluster_features_umap │
│ 456177 ┆ -1.330672 ┆ 11.763294 ┆ minnie65   ┆ csm_cluster_features_umap │
│ 461339 ┆ 0.901332  ┆ 0.765975  ┆ minnie65   ┆ csm_cluster_features_umap │
│ 302377 ┆ 0.538734  ┆ 1.066206  ┆ minnie65   ┆ csm_cluster_features_umap │
└────────┴───────────┴───────────┴────────────┴───────────────────────────┘

### Features x Descriptions for all featuresets concat without the featureset_id column

In [12]:
df_cellfeatureDef = pl.read_delta(os.path.join(DELTAS, 'cellfeaturedefinition'))
df_cellfeatureDef

shape: (87, 6)
┌──────────────────┬──────────────────────────┬────────────────┬───────────┬───────────┬───────────┐
│ id               ┆ description              ┆ unit           ┆ data_type ┆ range_min ┆ range_max │
│ ---              ┆ ---                      ┆ ---            ┆ ---       ┆ ---       ┆ ---       │
│ str              ┆ str                      ┆ str            ┆ str       ┆ f64       ┆ f64       │
╞══════════════════╪══════════════════════════╪════════════════╪═══════════╪═══════════╪═══════════╡
│ x_umap           ┆ umap low dimensional     ┆ ARBITRARY_UNIT ┆ <f4       ┆ null      ┆ null      │
│                  ┆ embedding…               ┆                ┆           ┆           ┆           │
│ y_umap           ┆ umap low dimensional     ┆ ARBITRARY_UNIT ┆ <f4       ┆ null      ┆ null      │
│                  ┆ embedding…               ┆                ┆           ┆           ┆           │
│ x_medial-lateral ┆ The x coordinate in      ┆ MICRONS_LENGTH ┆ <f4       ┆ null      ┆ null      │
│                  ┆ minnie65 a…              ┆                ┆           ┆           ┆           │
│ y_dorsal-ventral ┆ The y coordinate in      ┆ MICRONS_LENGTH ┆ <f4       ┆ null      ┆ null      │
│                  ┆ minnie65 a…              ┆                ┆           ┆           ┆           │
│ z_caudal-rostral ┆ The z coordinate in      ┆ MICRONS_LENGTH ┆ <f4       ┆ null      ┆ null      │
│                  ┆ minnie65 a…              ┆                ┆           ┆           ┆           │
│ …                ┆ …                        ┆ …              ┆ …         ┆ …         ┆ …         │
│ branch_svd3      ┆ SVD loading dendritic    ┆ RATIO          ┆ <f4       ┆ NaN       ┆ NaN       │
│                  ┆ path len…                ┆                ┆           ┆           ┆           │
│ branch_svd4      ┆ SVD loading dendritic    ┆ RATIO          ┆ <f4       ┆ NaN       ┆ NaN       │
│                  ┆ path len…                ┆                ┆           ┆           ┆           │
│ ego_count_pca0   ┆ PC loading synapse depth ┆ RATIO          ┆ <f4       ┆ NaN       ┆ NaN       │
│                  ┆ relat…                   ┆                ┆           ┆           ┆           │
│ ego_count_pca1   ┆ PC loading synapse depth ┆ RATIO          ┆ <f4       ┆ NaN       ┆ NaN       │
│                  ┆ relat…                   ┆                ┆           ┆           ┆           │
│ ego_count_pca2   ┆ PC loading synapse depth ┆ RATIO          ┆ <f4       ┆ NaN       ┆ NaN       │
│                  ┆ relat…                   ┆                ┆           ┆           ┆           │
└──────────────────┴──────────────────────────┴────────────────┴───────────┴───────────┴───────────┘

### Featuresets x Features

In [13]:
df_cellfeatureSet = pl.read_delta(os.path.join(DELTAS, 'cellfeatureset'))
df_cellfeatureSet

shape: (3, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ id                     ┆ description            ┆ feature_definition_ids ┆ extraction_method     │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ str                    ┆ str                    ┆ list[str]              ┆ str                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ csm_cluster_features_u ┆ Umap reduction fo the  ┆ ["x_umap", "y_umap"]   ┆ umap_learn            │
│ map                    ┆ features…              ┆                        ┆                       │
│ minnie65_std_transform ┆ The coordinates of the ┆ ["x_medial-lateral",   ┆ Applied               │
│ _coordin…              ┆ cell so…               ┆ "y_dorsal…             ┆ standard_transform to │
│                        ┆                        ┆                        ┆ …                     │
│ csm_cluster_features   ┆ Cell features used for ┆ ["nucleus_volume_um",  ┆ Aggegated and         │
│                        ┆ cluster…               ┆ "nucleus…              ┆ computed via htt…     │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

## Check existing patchseq features and featuresets, compare if feature names are consistent

In [18]:
df_visp_featdef_exc = pl.read_delta(os.path.join(VISP, 'cellfeatureset/visp_exc'))
df_visp_featdef_exc

shape: (1, 4)
┌────────────────────────────┬────────────────────┬───────────────────────────┬────────────────────┐
│ id                         ┆ description        ┆ feature_definition_ids    ┆ extraction_method  │
│ ---                        ┆ ---                ┆ ---                       ┆ ---                │
│ str                        ┆ str                ┆ list[str]                 ┆ str                │
╞════════════════════════════╪════════════════════╪═══════════════════════════╪════════════════════╡
│ exc_visp_morph_features    ┆ Cell features used ┆ ["apical_dendrite_bias_x" ┆ Computed via       │
│                            ┆ for analysi…       ┆ , "ap…                    ┆ https://github.co… │
└────────────────────────────┴────────────────────┴───────────────────────────┴────────────────────┘

In [19]:
df_visp_featdef_inh = pl.read_delta(os.path.join(VISP, 'cellfeatureset/visp_inh'))
df_visp_featdef_inh

shape: (1, 4)
┌─────────────────────────┬────────────────────┬────────────────────────┬────────────────────┐
│ id                      ┆ description        ┆ feature_definition_ids ┆ extraction_method  │
│ ---                     ┆ ---                ┆ ---                    ┆ ---                │
│ str                     ┆ str                ┆ list[str]              ┆ str                │
╞═════════════════════════╪════════════════════╪════════════════════════╪════════════════════╡
│ inh_visp_morph_features ┆ Cell features used ┆ ["axon_bias_x",        ┆ Computed via       │
│                         ┆ for analysi…       ┆ "axon_bias_y",…        ┆ https://github.co… │
└─────────────────────────┴────────────────────┴────────────────────────┴────────────────────┘

In [22]:
em_exc_list = df_feat_exc.columns[1:]
em_inh_list = df_feat_inh.columns[1:]
visp_exc_list = df_visp_featdef_exc['feature_definition_ids'][0]
visp_inh_list = df_visp_featdef_inh['feature_definition_ids'][0]

In [25]:
set(em_exc_list) == set(visp_exc_list)

False

In [26]:
set(em_inh_list) == set(visp_inh_list)

False

In [59]:
from itertools import zip_longest
def get_list_differences(list_a, list_b, buf=30):
    """
    Returns items unique to list_a and items unique to list_b.
    """
    set_a = set(list_a)
    set_b = set(list_b)
    
    only_in_a = list(set_a - set_b)
    only_in_b = list(set_b - set_a)
    
    print(f"{'ONLY IN A':<{buf}} | {'ONLY IN B':<{buf}}")
    print("-" * (2*buf))
    
    for a, b in zip_longest(only_in_a, only_in_b, fillvalue=""):
        print(f"{a:<{buf}} | {b:<{buf}}")

    print('\n')
    #return only_in_a, only_in_b

In [62]:
get_list_differences(em_exc_list, visp_exc_list)
get_list_differences(em_inh_list, visp_inh_list)

get_list_differences(visp_exc_list, visp_inh_list, buf=45)

ONLY IN A                      | ONLY IN B
------------------------------------------------------------
basal_dendrite_depth_pc_2      | axon_exit_distance
soma_surface_area              | axon_exit_theta
basal_dendrite_depth_pc_0      |
basal_dendrite_depth_pc_3      |
basal_dendrite_depth_pc_5      |
basal_dendrite_depth_pc_1      |
basal_dendrite_depth_pc_4      |


ONLY IN A                      | ONLY IN B
------------------------------------------------------------
basal_dendrite_depth_pc_2      |
basal_dendrite_depth_pc_0      |
basal_dendrite_depth_pc_3      |
basal_dendrite_depth_pc_1      |
basal_dendrite_depth_pc_4      |


ONLY IN A                                     | ONLY IN B
------------------------------------------------------------------------------------------
apical_dendrite_mean_contraction              | axon_depth_pc_4
apical_dendrite_std_moments_along_max_distance_projection | axon_frac_intersect_basal_dendrite
apical_dendrite_bias_y                        | axon_max_branch_order
apical_dendrite_max_branch_order              | axon_soma_percentile_y
apical_dendrite_bias_x                        | basal_dendrite_frac_above_axon
apical_dendrite_mean_diameter                 | axon_depth_pc_1
apical_dendrite_total_length                  | axon_emd_with_basal_dendrite
basal_dendrite_frac_below_apical_dendrite     | axon_bias_y
apical_dendrite_frac_below_basal_dendrite     | axon_max_euclidean_distance
apical_dendrite_max_euclidean_distance        | axon_extent_y
apical_dendrite_depth_pc_2                    | axon_total_length
apical_dendrite_total_surface_area            | axon_num_branches
apical_dendrite_num_outer_bifurcations        | axon_soma_percentile_x
apical_dendrite_frac_intersect_basal_dendrite | axon_depth_pc_5
apical_dendrite_mean_moments_along_max_distance_projection | axon_mean_contraction
apical_dendrite_max_path_distance             | axon_depth_pc_0
apical_dendrite_frac_above_basal_dendrite     | axon_frac_below_basal_dendrite
apical_dendrite_depth_pc_0                    | axon_frac_above_basal_dendrite
basal_dendrite_frac_above_apical_dendrite     | axon_depth_pc_3
apical_dendrite_soma_percentile_x             | axon_bias_x
apical_dendrite_depth_pc_1                    | axon_depth_pc_2
basal_dendrite_frac_intersect_apical_dendrite | basal_dendrite_frac_below_axon
apical_dendrite_depth_pc_3                    | axon_max_path_distance
apical_dendrite_extent_y                      | axon_extent_x
apical_dendrite_num_branches                  | basal_dendrite_frac_intersect_axon
apical_dendrite_soma_percentile_y             |
apical_dendrite_early_branch_path             |
apical_dendrite_emd_with_basal_dendrite       |
apical_dendrite_extent_x                      |

## Write the csvs to deltalakes
as a new featureset? or same as visp exc and inh morph sets?   
answer: write as a new feature set for minnie because of the differences   
later: a new combined feature set is to be expected